### ISSUE TITLE
Prototype trang chủ 

### ISSUE THREAD

**Issue by baotnq** [vinaas/medihub-prototype#2]
Show hình chụp trang chủ khi làm xong

**Comment by baotnq** [comment]
khi nào xong nhớ reply trên đây nghe

**Comment by gattadesmond** [comment]
![image](https://cloud.githubusercontent.com/assets/7348913/16510814/9e4c2578-3f73-11e6-948e-3470735adb70.png)

@baotnq a Bảo xem hình trang chủ

**Comment by baotnq** [comment]
good done!
