### ISSUE TITLE
Deplay static page lên gh-pages 

### ISSUE THREAD

**Issue by baotnq** [vinaas/medihub-prototype#3]
- copy build sang __PUBLIC
- chạy lệnh .bat để push lên gh-pages
- test lại với demo domain của github.io

**Comment by gattadesmond** [comment]
@baotnq e mới up lên, link : https://vinaas.github.io/medihub-prototype/
a Bảo xem lại cái lệnh push gh-pages, hiện tại em up bằng tay.

**Comment by baotnq** [comment]
ok em, làm bằng tay cho nhanh cũng được,
